# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_complete', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('pseudo', models.IntegerField(max_length=100)),
                ('nb_acces', models.CharField(max_length=10)),
            ],
        ),
    ]
