# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniurl',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='nb_acces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='pseudo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='url_complete',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
